"""Add the 'PaymentMethod' model with Patreon and GitHub

Revision ID: 0003
Revises: 0002
Create Date: 2024-11-17 10:49:59.514184
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: Union[str, None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_methods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("supports_payment_comments", sa.Boolean(), nullable=False),
        sa.Column("supports_tiers", sa.Boolean(), nullable=False),
        sa.Column("supports_one_time_payments", sa.Boolean(), nullable=False),
        sa.Column("minimum_one_time_payment_amount", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["creators.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payment_methods_github_sponsors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("github_id", sa.Integer(), nullable=False),
        sa.Column("github_login", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["payment_methods.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment_methods_github_sponsors")
    op.drop_table("payment_methods")
    # ### end Alembic commands ###
