"""Add Patreon, make fields required

Revision ID: 0004
Revises: 0003
Create Date: 2024-11-20 19:08:26.227206
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: Union[str, None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_methods_patreon",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patreon_creator_slug", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["payment_methods.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment_methods_patreon")
    # ### end Alembic commands ###
