"""Add Payment.state

Revision ID: 0007
Revises: 0006
Create Date: 2024-11-29 16:42:50.216593
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: Union[str, None] = "0006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "state",
                sa.Enum(
                    "next",
                    "unpaid",
                    "paid",
                    name="payment_status",
                    create_constraint=True,
                ),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_column("state")

    # ### end Alembic commands ###
