"""Add BudgetAlloc to Supporter

Revision ID: 0008
Revises: 0007
Create Date: 2024-11-29 22:04:53.461827
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import app

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: Union[str, None] = "0007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budget_allocations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("supporter_id", sa.Integer(), nullable=False),
        sa.Column("allocation_amount", sa.Integer(), nullable=False),
        sa.Column("created_at", app.TzAwareDatetime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["supporter_id"],
            ["supporters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("supporters", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("created_at", app.TzAwareDatetime(timezone=True), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("supporters", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    op.drop_table("budget_allocations")
    # ### end Alembic commands ###
