"""Record the last BudgetAllocation amount

Revision ID: 0009
Revises: 0008
Create Date: 2024-12-05 22:57:56.041836
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_allocations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('undistributed_amount', sa.Integer(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_allocations', schema=None) as batch_op:
        batch_op.drop_column('undistributed_amount')

    # ### end Alembic commands ###
